#!/usr/bin/env bun
/**
 * Post-generation script to create barrel files for Orval output.
 *
 * Orval's tags-split mode generates tag/tag.ts but no index.ts barrel.
 * This script creates the barrel file to enable clean imports:
 *   import { useUsers, useAuth } from './generated/api'
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

const API_DIR = path.resolve(__dirname, '../src/generated/api');

function generateBarrel(): void {
  if (!fs.existsSync(API_DIR)) {
    console.error(`API directory not found: ${API_DIR}`);
    process.exit(1);
  }

  const entries = fs.readdirSync(API_DIR, { withFileTypes: true });
  const folders = entries.filter((e) => e.isDirectory()).map((e) => e.name);

  const exports = folders.map((folder) => `export * from "./${folder}/${folder}";`).join('\n');

  const content = `/**
 * Generated by scripts/generate-barrel.ts
 * Do not edit manually.
 */

${exports}
`;

  const indexPath = path.join(API_DIR, 'index.ts');
  fs.writeFileSync(indexPath, content);

  console.log(`✓ Generated barrel file with ${folders.length} exports`);
}

generateBarrel();
