export { AtsSection } from "./ats-section";
export { ComparisonSection } from "./comparison-section";
export { CtaGenericSection } from "./cta-generic-section";
export { FocoSection } from "./foco-section";
export { FooterSection } from "./footer-section";
export { HeroSection } from "./hero-section";
export { HookSection } from "./hook-section";
export { HowItWorksSection } from "./how-it-works-section";
export { PainMarketSection } from "./pain-market-section";
export { PainClosingSection, PainTimeSection } from "./pain-time-section";
export { PipelineSection } from "./pipeline-section";
export { PricingSection } from "./pricing-section";
export { SectionLabel } from "./section-label";
export { TestimonialsSection } from "./testimonials-section";
