name: CI

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [dev]

permissions:
  contents: read
  actions: read
  packages: read

jobs:
  ci:
    uses: octopus-synapse/octopus-workflows/.github/workflows/ci.yml@main
    with:
      node-version: "20"
      package-manager: "pnpm"
      has-database: false
      has-redis: false
      build-output-dir: ".next"
    secrets: inherit
